env:
  node: true
  es6: true
  mocha: true
extends: [
  'eslint:recommended'
]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    modules: true
    experimentalObjectRestSpread: true
  ecmaVersion: 2018
  sourceType: module
rules:
  indent: [
    error, 
    tab, 
    {SwitchCase: 1}
  ]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never